services:
    rabitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - "5672:5672"
          - "15672:15672"
    mongodb:
        image: mongo
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=mongopw
        volumes:
          - mongodata:/var/lib/mongodb/data
    postgres:
        image: postgres
        environment:
          - POSTGRES_PASSWORD=postgrespw
        ports:
          - "5432:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
    mongodata: